language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
git:
  depth: false
  quiet: true
env:
  global:
    - ARDUINO_IDE_VERSION="1.8.4"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - mkdir -p ~./arduino_ide/libraries/
  - cd ~./arduino_ide/libraries/
  - git clone https://github.com/PaulStoffregen/Time.git
  - git clone https://github.com/gmag11/NtpClient.git
  - git clone https://github.com/thomasfredericks/Bounce2.git
  - git clone https://github.com/knolleary/pubsubclient.git
  - git clone https://github.com/tilutza/aJson.git
  - git clone https://github.com/tilutza/RemoteDebug.git
  - cd -
script:
  - build_platform esp8266
